name: Deploy to Google App Engine

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: 'Deploying to Google Cloud'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0
        with:
          project_id: tech-snacks
          deliverables: app.yaml

      - name: Health check
        run: 'curl "${{ steps.deploy.outputs.url }}"'
